services:
  mc-server:
    build: .
    ports:
      - "8888:25565"
    env_file:
      - .env
    environment:
      - ENABLE_EULA=${ENABLE_EULA}
      - XMS=${XMS}
      - XMX=${XMX}
      - SERVER_PORT=${SERVER_PORT}
      - ONLINE_MODE=${ONLINE_MODE}
      - ENABLE_QUERY=${ENABLE_QUERY}
      - QUERY_PORT=${QUERY_PORT}
      - MOTD=${MOTD}
    volumes:
      - mc_data:/data
    restart: unless-stopped

volumes:
  mc_data:
