version: '3.8'
services:
  mc-server:
    build: .
    user: "10001:10001"
    ports:
      - "8888:25565"
    environment:
      - EULA=true
    volumes:
      - ./data:/data
    restart: unless-stopped
